spring:
  application:
    name: zipkin-service
  cloud:
    config:
      profile: dev
      discovery:
        enabled: true
        serviceId: config-service

server:
  port: 8721

management:
  security:
    enabled: false

eureka:
  instance:
    lease-expiration-duration-in-seconds:  90 # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 30 # 续约到期时间（默认90秒）
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:8701/eureka/
    healthcheck:
      enabled: true
